### PR TITLE
change controller name from gripper to sdh

### PR DESCRIPTION
**Pull request by sthoduka**
Required because of this commit: a8e28a811112afa7af36f50dc344853b2c860343

### CODE REVIEW

**Comment by frederikhegger** [comment]
Hey Santosh, I was not aware of this pull request. Let's see if this is still need after the upgrade to indigo

**Comment by sthoduka** [comment]
yup ok. This was when I was trying to it to work in simulation. I don't know whether it's required on the robot.

**Comment by frederikhegger** [comment]
On the real robot it is not necessary. I will merge the recent changes of the cob_simulation repository into our fork and check then the simulation.

**Comment by frederikhegger** [comment]
We tested everything on the real robot and in simulation. It seems that it is not needed

**Pull request closed without merging**
